version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: booking-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - booking
    restart: unless-stopped


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/booking
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
    ports:
      - "8070:8070"
    networks:
      - booking
    depends_on:
      - postgres

  hotelmanager:
    build:
      context: ./hotelmanager
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/booking
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
    ports:
      - "8090:8090"
    networks:
      - booking
    depends_on:
      - postgres


networks:
  booking:

volumes:
  pgdata:
