openapi: "3.1.0"
info:
  title: "Bookings_microservices API"
  description: "Bookings_microservices API"
  version: "1.0.0"
servers:
  - url: "https://Bookings_microservices"
paths:
  /api/client/{clientId}/reservations:
    get:
      summary: "GET api/client/{clientId}/reservations"
      operationId: "findReservations"
      parameters:
        - name: "clientId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/BookingForClientDto"
components:
  schemas:
    BigDecimal:
      type: "object"
      properties: { }
    BookingForClientDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        startDate:
          type: "string"
          format: "date-time"
        endDate:
          type: "string"
          format: "date-time"
        discountPercent:
          $ref: "#/components/schemas/BigDecimal"
        bookingStatus:
          type: "string"
          enum:
            - "CONFIRMED"
            - "CANCELLED"
        totalPrice:
          $ref: "#/components/schemas/BigDecimal"
        hotel:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
        currentPrice:
          $ref: "#/components/schemas/BigDecimal"
        roomType:
          type: "string"
          enum:
            - "SINGLE"
            - "DOUBLE"