openapi: "3.1.0"
info:
  title: "Bookings_microservices API"
  description: "Bookings_microservices API"
  version: "1.0.0"
servers:
  - url: "https://Bookings_microservices"
paths:
  /api/booking/room:
    post:
      summary: "POST api/booking/room"
      operationId: "reservationHotels"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reservationHotelDto"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
components:
  schemas:
    reservationHotelDto:
      type: "object"
      properties:
        roomId:
          type: "integer"
          format: "int32"
        startDate:
          type: "string"
          format: "date-time"
        endDate:
          type: "string"
          format: "date-time"