eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client
          uri: http://localhost:8070
          predicates:
            - Path=/api/client/**
            - Path=/api/search/**
            - Path=/api/booking/room
        - id: hotelmanager
          uri: http://localhost:8090
          predicates:
            - Path=/api/manager/**